export default Status_Database = [
    {
        id: 1,
        title: ' #1 Dewpoint sensor is broken',
        info: 'Please check this component...',
        date: '16/10/23',
        time: '13:21',
        country: 'Turkiye',
        customer: 'Customer A',
        site: 'Site 1',
        device: 'Device A',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 1,
        title: ' #1 Dewpoint sensor is broken',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '10:16',
        country: 'Turkiye',
        customer: 'Customer A',
        site: 'Site 1',
        device: 'Device A',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 1,
        title: ' #1 Dewpoint sensor is broken',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '15:49',
        country: 'Turkiye',
        customer: 'Customer A',
        site: 'Site 1',
        device: 'Device A',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 1,
        title: ' #1 Dewpoint sensor is broken',
        info: 'Please check this component...',
        date: '12/10/23',
        time: '09:05',
        country: 'Turkiye',
        customer: 'Customer A',
        site: 'Site 1',
        device: 'Device A',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 6,
        title: " #6 Air pressure filter blocked",
        info: 'Please check this component...',
        date: '14/10/23',
        time: '23:12',
        country: 'India',
        customer: 'Customer F',
        site: 'Site 6',
        device: 'Device F',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 6,
        title: " #6 Air pressure filter blocked",
        info: 'Please check this component...',
        date: '14/10/23',
        time: '20:11',
        country: 'India',
        customer: 'Customer F',
        site: 'Site 6',
        device: 'Device F',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 6,
        title: " #6 Air pressure filter blocked",
        info: 'Please check this component...',
        date: '14/10/23',
        time: '19:00',
        country: 'India',
        customer: 'Customer F',
        site: 'Site 6',
        device: 'Device F',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alarm-light',
        color: '#E74C3C',
    },
];