export default Status_Database = [
    {
        id: 1,
        title: ' #1 Dewpoint sensor is broken',
        info: 'Please check this component...',
        date: '16/10/23',
        time: '13:21',
        country: 'Turkiye',
        customer: 'Customer A',
        site: 'Site 1',
        device: 'Device A',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 2,
        title: ' #2 Steam valve is leaking',
        info: 'Please check this component...',
        date: '16/10/23',
        time: '12:10',
        country: 'Bulgaria',
        customer: 'Customer B',
        site: 'Site 2',
        device: 'Device B',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
    },
    {
        id: 3,
        title: ' #3 Heater is broken',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '18:13',
        country: 'Iceland',
        customer: 'Customer C',
        site: 'Site 3',
        device: 'Device C',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
    },
    {
        id: 4,
        title: ' #4 Oil filter is blocked',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '11:01',
        country: 'China',
        customer: 'Customer D',
        site: 'Site 4',
        device: 'Device D',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
    },
    {
        id: 5,
        title: ' #5 Thermal oil valve is leaking',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '08:09',
        country: 'Spain',
        customer: 'Customer E',
        site: 'Site 5',
        device: 'Device E',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
    {
        id: 6,
        title: " #6 Air pressure filter blocked",
        info: 'Please check this component...',
        date: '14/10/23',
        time: '23:12',
        country: 'India',
        customer: 'Customer F',
        site: 'Site 6',
        device: 'Device F',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alarm-light',
        color: '#E74C3C',
    },
    {
        id: 7,
        title: ' #7 Belt stopped during heating',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '19:19',
        country: 'France',
        customer: 'Customer G',
        site: 'Site 7',
        device: 'Device G',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
    },
    {
        id: 8,
        title: ' #8 Tank water level is too low',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '17:15',
        country: 'USA',
        customer: 'Customer H',
        site: 'Site 8',
        device: 'Device H',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
    },
    {
        id: 9,
        title: ' #9 Exhaust valve is not working',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '13:00',
        country: 'Brazil',
        customer: 'Customer I',
        site: 'Site 9',
        device: 'Device I',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'check-circle',
        color: '#28B463',
    },
    {
        id: 10,
        title: ' #10 Steam valve is broken',
        info: 'Please check this component...',
        date: '13/10/23',
        time: '17:30',
        country: 'Germany',
        customer: 'Customer J',
        site: 'Site 10',
        device: 'Device J',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
];