export default Warning_Database = [
    {
        id: 5,
        title: ' #5 Thermal oil valve is leaking',
        info: 'Please check this component...',
        date: '15/10/23',
        time: '08:09',
        country: 'Spain',
        customer: 'Customer E',
        site: 'Site 5',
        device: 'Device E',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
    {
        id: 5,
        title: ' #5 Thermal oil valve is leaking',
        info: 'Please check this component...',
        date: '14/10/23',
        time: '01:09',
        country: 'Spain',
        customer: 'Customer E',
        site: 'Site 5',
        device: 'Device E',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
    {
        id: 5,
        title: ' #5 Thermal oil valve is leaking',
        info: 'Please check this component...',
        date: '13/10/23',
        time: '18:18',
        country: 'Spain',
        customer: 'Customer E',
        site: 'Site 5',
        device: 'Device E',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
    {
        id: 5,
        title: ' #5 Thermal oil valve is leaking',
        info: 'Please check this component...',
        date: '12/10/23',
        time: '21:09',
        country: 'Spain',
        customer: 'Customer E',
        site: 'Site 5',
        device: 'Device E',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
    {
        id: 10,
        title: ' #10 Steam valve is broken',
        info: 'Please check this component...',
        date: '13/10/23',
        time: '17:30',
        country: 'Germany',
        customer: 'Customer J',
        site: 'Site 10',
        device: 'Device J',
        image: "https://marel.com/media/vt2hui0g/industrial-oven-modularoven.jpg",
        icon: 'alert',
        color: '#F39C12',
    },
];